back/src/Entity/User.php
<?php


namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Table(name="user")
 * @UniqueEntity(fields="email")
 * @ORM\Entity()
 */
class User implements UserInterface, \Serializable {

    const CIVILITE = [
        0 => 'Monsieur',
        1 => 'Madame',
        2 => 'Mademoiselle'
    ];

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(max=250)
     */
    private $plainPassword;

    /**
     * The below length depends on the "algorithm" you use for encoding
     * the password, but this works well with bcrypt.
     *
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(name="roles", type="array")
     */
    private $roles = array();

    /**
     * @ORM\Column(type="integer", options={"default": 0})
     */
    private $civilite = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank()
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank()
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     * @Assert\Regex("/^[0-9]{10}$/")
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=120, nullable=true)
     * @Assert\Length(min=5, max=120)
     */
    private $adresse_1;

    /**
     * @ORM\Column(type="string", length=120, nullable=true)
     * @Assert\Length(min=5, max=120)
     */
    private $adresse_2;

    /**
     * @ORM\Column(type="string", length=5, nullable=true)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=120, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=120, nullable=true)
     * @Assert\Length(min=5, max=120)
     */
    private $poste_recherche;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=120, nullable=true)
     * @Assert\Length(min=5, max=120)
     */
    private $statut;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default": false})
     */
    private $mobilite;

    /**
     * @ORM\Column(type="string", length=120, nullable=true)
     * @Assert\Length(min=5, max=120)
     */
    private $mobilite_zone;

    /**
     * @ORM\Column(type="string", length=4000, nullable=true)
     * @Assert\Length(min=10)
     */
    private $notes;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Formation", mappedBy="candidat", cascade={"persist"})
     */
    private $formations;


    public function __construct() {
        $this->date_creation = new \DateTime('now', new \DateTimeZone('Europe/Paris'));
        $this->formations = new ArrayCollection();
        $this->isActive = true;
    }


    function getId() {
        return $this->id;
    }

    function getEmail() {
        return $this->email;
    }
    
    public function getRoles() {
        return $this->roles;
    }

    function getPlainPassword() {
        return $this->plainPassword;
    }

    function getIsActive() {
        return $this->isActive;
    }

    public function getUsername() {
        return $this->email;
    }

    public function getPassword() {
        return $this->password;
    }

    function addRole($role) {
        $this->roles[] = $role;
    }

    function removeRoles() {
        foreach($this->roles as $k=>$role) {
            unset($this->roles[$k]);
        }
    }

    public function eraseCredentials() {
       
    }
    public function getSalt() {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    /** @see \Serializable::serialize() */
    public function serialize() {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
            $this->isActive,
                // see section on salt below
                // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized) {
        list (
                $this->id,
                $this->email,
                $this->password,
                $this->isActive,
                ) = unserialize($serialized);
    }


    public function getCivilite(): ?int
    {
        return $this->civilite;
    }

    public function getNom() {
        return $this->nom;
    }

    public function getPrenom() {
        return $this->prenom;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function getPosteRecherche(): ?string
    {
        return $this->poste_recherche;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function getMobilite(): ?bool
    {
        return $this->mobilite;
    }

    public function getMobiliteZone(): ?string
    {
        return $this->mobilite_zone;
    }

    public function getAdresse1(): ?string
    {
        return $this->adresse_1;
    }

    public function getAdresse2(): ?string
    {
        return $this->adresse_2;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }


    function setId($id) {
        $this->id = $id;
    }

    public function setEmail(string $email): self
    {
        $this->email = strtolower(trim($email));
        return $this;
    }

    function setPlainPassword($plainPassword) {
        $this->plainPassword = $plainPassword;
    }

    function setPassword($password) {
        $this->password = $password;
    }

    function setIsActive($isActive) {
        $this->isActive = $isActive;
    }


    public function setCivilite(int $civilite): self
    {
        $this->civilite = $civilite;
        return $this;
    }

    public function setNom(string $nom): self
    {
        $nom = str_ireplace('-', ' ', $nom);
        $nom = str_ireplace('  ', ' ', $nom);
        $this->nom = strtoupper(trim($nom));
        return $this;
    }

    public function setPrenom(string $prenom): self
    {
        $prenom = str_ireplace('-', ' ', $prenom);
        $prenom = str_ireplace('  ', ' ', $prenom);
        $prenom = ucwords(strtolower(trim($prenom)));
        $this->prenom = str_ireplace(' ', '-', $prenom);
        return $this;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = trim($telephone);
        return $this;
    }

    public function setAdresse1(string $adresse_1): self
    {
        $this->adresse_1 = trim($adresse_1);
        return $this;
    }

    public function setAdresse2(string $adresse_2): self
    {
        $this->adresse_2 = trim($adresse_2);
        return $this;
    }

    public function setCp(string $cp): self
    {
        $this->cp = trim($cp);
        return $this;
    }
    
    public function setVille(string $ville): self
    {
        $this->ville = mb_strtoupper(trim($ville));
        return $this;
    }
    
    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;
        return $this;
    }

    public function setMobilite(bool $mobilite): self
    {
        $this->mobilite = $mobilite;
        return $this;
    }

    public function setMobiliteZone(string $mobilite_zone): self
    {
        $this->mobilite_zone = trim($mobilite_zone);
        return $this;
    }

    public function setNotes(string $notes): self
    {
        $this->notes = trim($notes);
        return $this;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = mb_strtoupper(trim($statut));
        return $this;
    }

    public function setPosteRecherche(string $poste_recherche): self
    {
        $this->poste_recherche = mb_strtoupper(trim($poste_recherche));
        return $this;
    }
    public function getSlug(): string {
        $slug = new Slugify();
        return $slug->slugify($this->nom . ' ' . $this->prenom);
    }

    public function getFormattedDateCreation() : string {
        return date_format($this->date_creation, 'd/m/Y H:i');
    }

    public function getFormattedCivilite(): ?string
    {
        return self::CIVILITE[$this->getCivilite()];
    }

    public function getFormattedDateNaissance() : string {
        return date_format($this->date_naissance, 'd/m/Y H:i');
    }

    public function getAge(): ?string
    {
        $now = new \Datetime('now');
        return $now->diff($this->date_naissance)->format("%Y");
    }

    public function getFirstLetter(): ?string
    {
        return substr($this->nom, 0, 1) . '.';
    }

    /**
     * @return Collection|Formation[]
     */
    public function getFormations(): Collection
    {
        return $this->formations;
    }

    public function addFormation(Formation $formation): self
    {
        if (!$this->formations->contains($formation)) {

back/src/Controller/cv/FormationController.php
<?php

namespace App\Controller\cv;

use App\Entity\Formation;
use App\Form\FormationType;
use App\Repository\FormationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/formation")
 */
class FormationController extends AbstractController
{
    const ROUTE_SHOW                = "formation.show";
    const ROUTE_ADD                 = "formation.add";
    const ROUTE_EDIT                = "formation.edit";
    const ROUTE_DELETE              = "formation.delete";
    const ROUTE_LIST                = "formation.list";
    const ROUTE_PRINT               = "formation.print";

    const TEMPLATE_EDIT_PATH        = "cv/formation/edit.html.twig";
    const TEMPLATE_ADD_PATH         = "cv/formation/add.html.twig";
    const TEMPLATE_LIST_PATH        = "cv/formation/list.html.twig";
    const TEMPLATE_SHOW_PATH        = "cv/formation/show.html.twig";

    const MENU                      = 'formation';
    /**
     * @Route("/list", name="formation.list", methods={"GET"})
     */
    public function list(FormationRepository $formationRepository): Response
    {
        return $this->render(self::TEMPLATE_LIST_PATH, [
            'formations' => $formationRepository->findByCandidat($this->getUser()),
            'menu' => self::MENU
        ]);
    }

    /**
     * @Route("/add", name="formation.add", methods={"GET","POST"})
     */
    public function add(Request $request): Response
    {
        $formation = new Formation();
        if (is_null($formation->getCandidat())) $formation->setCandidat($this->getUser());
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($formation);
            $entityManager->flush();

            return $this->redirectToRoute(self::ROUTE_LIST);
        }

        return $this->render(self::TEMPLATE_ADD_PATH, [
            'formation' => $formation,
            'form' => $form->createView(),
            'menu' => self::MENU
        ]);
    }

    /**
     * @Route("/{id}", name="formation.show", methods={"GET"})
     */
    public function show(Formation $formation): Response
    {
        return $this->render(self::TEMPLATE_SHOW_PATH, [
            'formation' => $formation,
            'menu' => self::MENU
        ]);
    }

    /**
     * @Route("/edit/{id}", name="formation.edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Formation $formation): Response
    {
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute(self::ROUTE_LIST);
        }

        return $this->render(self::TEMPLATE_EDIT_PATH, [
            'formation' => $formation,
            'form' => $form->createView(),
            'menu' => self::MENU    
        ]);
    }

    /**
     * @Route("/delete/{id}", name="formation.delete", methods={"DELETE"})
     */
    public function delete(Request $request, Formation $formation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($formation);
            $entityManager->flush();
        }

        return $this->redirectToRoute(self::ROUTE_LIST);
    }
}

back/templates/cv/profil/add.html.twig
{% extends 'base.html.twig' %}
{% block title %}
Candidat
{% endblock %}


{% block menu %}
{{ include ("users/menu.html.twig") }}
{% endblock %}

{% block body %}
<div class="container mt-4">

    <h1>Nouveau candidat</h1>

    {{ include('humanRessources/candidat/cvForm.html.twig', {form: form}) }}

</div>
{% endblock %}

back/templates/cv/profil/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}
{{candidat.slug}}
{% endblock %}


{% block menu %}
{{ include ("users/menu.html.twig") }}
{% endblock %}

{% block body %}
<div class="container mt-4">

    <h1>Modifier le profil de {{ candidat.prenom }} {{ candidat.nom }}</h1>

    {{ include('cv/profil/form.html.twig', {form: form}) }}

</div>
{% endblock %}

back/templates/cv/profil/form.html.twig
    {{ form_start(form) }}
        <div class="row">
            <div class="col-md-2">{{ form_row(form.civilite) }}</div>
            <div class="col-md-3">{{ form_row(form.nom) }}</div>
            <div class="col-md-3">{{ form_row(form.prenom) }}</div>
        </div>
        <div class="row">
            <div class="col-md-8">{{ form_row(form.statut) }}</div>
        </div>
        <div class="row">
            <div class="col-md-8">{{ form_row(form.poste_recherche) }}</div>
        </div>
        <div class="row">
            <div class="col-md-4">{{ form_row(form.telephone) }}</div>
            <div class="col-md-4">{{ form_row(form.email) }}</div>
        </div>
        <div class="row">
            <div class="col-md-8">{{ form_row(form.adresse_1) }}</div>
        </div>
        <div class="row">
            <div class="col-md-8">{{ form_row(form.adresse_2) }}</div>
        </div>
        <div class="row">
            <div class="col-md-2">{{ form_row(form.cp) }}</div>
            <div class="col-md-6">{{ form_row(form.ville) }}</div>
        </div>
        <div class="row">
            <div class="col-md-1">{{ form_row(form.mobilite) }}</div>
            <div class="col-md-7">{{ form_row(form.mobilite_zone) }}</div>
        </div>
        <div class="row">
            <div class="col-md-8">{{ form_row(form.notes) }}</div>
        </div>
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary">Sauvegarder</button>
        {% if is_granted('ROLE_HR') %}
            <a class="btn btn-primary" href="{{ path('profil.list') }}" role="button">Annuler</a>
        {% else %}
            <a class="btn btn-primary" href="{{ path('candidat.home') }}" role="button">Annuler</a>
        {% endif %}
    {{ form_end(form) }}

back/templates/cv/profil/list.html.twig
{% extends 'base.html.twig' %}
{% block title %}
Candidats
{% endblock %}


{% block menu %}
{{ include ("users/menu.html.twig") }}
{% endblock %}
{% block body %}
<div class="container mt-4">

    <h1>Gérer les Candidats</h1>

    {% for message in app.flashes('success') %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
     
    <div class='jumbotron'>
        <div class='container'>
            {{ form_start(form) }}
            <div class="form-row">
                <div class="col">
                    {{ form_row(form.cp) }}
                </div>
                <div class="col">
                    {{ form_row(form.nom) }}
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-primary">Rechercher</button>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <table class="table table-stripped">
        <thead>
            <tr>
                <th>Candidats</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for candidat in candidats %}
            <tr>
                <td>{{ candidat.nom }} {{ candidat.prenom }}</td>
                <td>{{ candidat.statut }}</td>
                <td>{{ candidat.cp }}</td>
                <td>{{ candidat.ville }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('profil.edit', {slug: candidat.slug, id: candidat.id} ) }}" role="button">Editer</a>
                    <form style="display: inline-block" method="post" onsubmit="return confirm('Confirmez-vous la suppression du candidat ?')" action="{{ path('profil.delete', {id: candidat.id} ) }}">
                        <input type="hidden" name="_method" value="DELETE" />
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidat.id) }}" />
                        <button type="submit" class="btn btn-primary" >Supprimer</button>
                    </form>
                    <a class="btn btn-primary" href="{{ path('profil.show', {slug: candidat.slug, id: candidat.id} ) }}" role="button">Afficher</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        {{ knp_pagination_render(candidats) }}
    </div>
</div>
{% endblock %}

back/templates/cv/profil/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}
{{ candidat.slug }}
{% endblock %}



{% block menu %}
{{ include ("users/menu.html.twig") }}
{% endblock %}

{% block body %}
<div class="jumbotron text-center">

    <h1>{{ candidat.prenom }} {{ candidat.nom }}</h1>

</div>

<div class="container">

    <div class="row">

        <div class="col-md-2">
            <div>N°, créé le </div>
            <div>Prénom, Nom</div>
            <div>Téléphone</div>
            <div>Email</div>
            <div>Date de naissance</div>
            <div>Adresse1</div>
            <div>Adresse2</div>
            <div>CP, ville</div>
            <div>Titre, Poste visé</div>
            <div>Mobilité</div>
            <div>Notes</div>
        </div>
         
        <div class="col-md-8">
            <div>{{ candidat.id }} - {{ candidat.formattedDateCreation }}</div>
            <div>{{ candidat.formattedCivilite }} {{ candidat.prenom }} {{ candidat.nom }}</div>
            <div>{{ candidat.telephone }}</div>
            <div>{{ candidat.email }}</div>
            <div>{{ candidat.formattedDateNaissance }}</div>
            <div>{{ candidat.adresse1 }}</div>
            <div>{{ candidat.adresse2 }}</div>
            <div>{{ candidat.cp }} {{ candidat.ville }}</div>
            <div>{{ candidat.statut }} {{ candidat.posteRecherche }}</div>
            <div>{% if candidat.mobilite %} {{ candidat.mobiliteZone }} {% else %} Non {% endif %}</div>
            <div>{{ candidat.notes }}</div> 
        </div> 
    </div>

    <a class="btn btn-primary" href="{{ path('profil.print', {slug: candidat.slug, id: candidat.id} ) }}" role="button" target="_blank">Visualiser<a>
</div>
{% endblock %}